### ISSUE TITLE
z_hook is not z_hook

### ISSUE THREAD

**Issue by VXACDev** [Oliver-1-1/ModuleSpoof#2]
You're using "Lighthook" -- don't steal code.

Also, your version of "z_hook" (stolen Lighthook) is "old" and has bugs with hooking -- I would go get the original, and latest version... you can reference my issue-report, and look for "48"

**Comment by Oliver-1-1** [comment]
credits are in code. https://github.com/Oliver-1-1/ModuleSpoof/blob/63f20af7502288e9e6f7c88dc368e8f49ec828ba/ModuleSpoof/z_hook.cpp#L67
